; Example config.ini for use with the client.py
[POWERDOG]
; address (optional, detected if not provided) the BLE address for the device GATT server
address = AA:BB:CC:DD:EE:FF
; service (optional, detected if not provided) UUID string that references the GATT service for notify data
service = 0000ffe2-0000-1000-8000-00805f9b34fb
; data sent to MQTT is limited within the range limits provided
; limit_voltage_range (optional, default=3.0) send data only when last sent value has changed more than the given range
limit_voltage_range = 3.0
; limit_amperage_range (optional, default=3.0) send data only when last sent value has changed more than the given range
limit_amperage_range = 3.0
; limit_wattage_range (optional, default=0.0) send data only when last sent value has changed more than the given range
limit_wattage_range = 0.0
; limit_quiet_sec (optional, default=60.0) if none of the range triggers have caused data to be sent within the given seconds, then send
limit_quiet_sec = 60.0
; device_meta_path (optional) path to write the JSON that is generated from the BLE device, used for general information and debugging
device_meta_path = data/device_meta.json

[BROKER]
; host (required, if not provided will skip connecting to MQTT) MQTT host name or IP
host = localhost
; port (optional, defaults to 1883) MQTT port is an integer
port = 1883
; user, MQTT authentication username, if omitted defaults to no authentication
user = my_username
; pass, MQTT authentication username, if omitted defaults to no authentication
pass = my_password
; subscribe_topics (optional) comma separated list of topics that will create logs if a subscribed message is received
subscribe_topics = powerdog/L1/voltage,powerdog/L1/amperage,powerdog/L1/wattage,powerdog/L1/power_usage,powerdog/L1/error,powerdog/L2/voltage,powerdog/L2/amperage,powerdog/L2/wattage,powerdog/L2/power_usage,powerdog/L2/error

[CLIENT]
; log_level (optional) changes log level for all Logger's used
log_level = INFO
