; Example config.ini for use with the client.py
[POWERDOG]
; address is the BLE address for the Watchdog GATT server
address = AA:BB:CC:DD:EE:FF
; service is a UUID string that references the Watchdog GATT service for notify data
service = 0000ffe2-0000-1000-8000-00805f9b34fb

[BROKER]
; MQTT host name or IP, defaults to localhost
host = 192.168.50.45
; MQTT port is an integer, defaults to 1883
port = 1883
; MQTT authentication username, if omitted defaults to no authentication
user = my_username
; MQTT authentication username, if omitted defaults to no authentication
pass = my_password
; subscribe_topics comma separated list of topics
subscribe_topics = powerdog/L1/voltage,powerdog/L1/amperage,powerdog/L1/wattage,powerdog/L1/power_usage,powerdog/L1/error,powerdog/L2/voltage,powerdog/L2/amperage,powerdog/L2/wattage,powerdog/L2/power_usage,powerdog/L2/error

[CLIENT]
log_level = INFO
